export const sample_foods = [
    {
        id: '1',
        name: 'MilkShake da Barbie',
        cookTime: '5-10',
        price: 10,
        favorite: false,
        origins: ['Mattel'],
        stars: 4.5,
        imageUrl: '/foods/food-1.jpg', 
        tags: ['FastFood', 'Frio'],
    },
    {
        id: '2',
        name: 'Frappucino do Ken',
        cookTime: '10-15',
        price: 8,
        favorite: true,
        origins: ['Mattel'],
        stars: 3.5,
        imageUrl: '/foods/food-2.jpg', 
        tags: ['FastFood', 'Café'],
    },
    {
        id: '3',
        name: 'Pipoca da Barbie',
        cookTime: '5-10',
        price: 15,
        favorite: false,
        origins: ['Mattel'],
        stars: 2.5,
        imageUrl: '/foods/food-3.jpg',
        tags: ['FastFood', 'Pipoca'],
    },
    {
        id: '4',
        name: 'Donuts Kenought',
        cookTime: '10-20',
        price: 15,
        favorite: true,
        origins: ['Mattel'],
        stars: 4.5,
        imageUrl: '/foods/food-4.jpg', 
        tags: ['SlowFood', 'Donuts', 'Lanche'],
    },
    {
        id: '5',
        name: 'Batatas da Barbie',
        cookTime: '10-15',
        price: 10,
        favorite: false,
        origins: ['Mattel'],
        stars: 4,
        imageUrl: '/foods/food-5.jpg', 
        tags: ['SlowFood', 'Frito', 'Lanche'],
    },
    {
        id: '6',
        name: 'Combo Barbieland',
        cookTime: '30-40',
        price: 75,
        favorite: true,
        origins: ['Mattel'],
        stars: 5,
        imageUrl: '/foods/food-6.jpg',
        tags: ['SlowFood', 'Lanche'],
    },
    {
        id: '7',
        name: 'Hamburguer da Barbie',
        cookTime: '10-20',
        price: 25,
        favorite: true,
        origins: ['Mattel'],
        stars: 4.5,
        imageUrl: '/foods/food-7.jpg', 
        tags: ['SlowFood', 'Lanche'],
    }
];

export const sample_tags = [
    {name: 'Tudo', count: 7},
    {name: 'FastFood', count: 3},
    {name: 'Frio', count: 1},
    {name: 'Lanche', count: 4},
    {name: 'SlowFood', count: 4},
    {name: 'Frito', count: 1},
    {name: 'Café', count: 1},
    {name: 'Donuts', count: 1},
    {name: 'Pipoca', count: 1},
]
